### ISSUE TITLE
Implement process end

### ISSUE THREAD

**Issue by philipheimboeck** [flomath/fluxos#23]
Currently no process may ever end, because it will result in an exception. We should implement an process cleanup handler that will be executed when a process ends.
- Link by adding the handler to the LR of a newly created process
- Free process space 
- Allow new processes to use the free slot

**Comment by nino-s** [comment]
mmu frees the process space - if a new process is added, mmu looks for free space(which can also be added onto killed process memory space)

**Comment by nino-s** [comment]
scheduler process kill need to be extracted as syscall
